/** Declaration file generated by dts-gen */

export = fast_json_stable_stringify;

declare function fast_json_stable_stringify(data: any, opts: any): any;

declare namespace fast_json_stable_stringify {
    const prototype: {
    };

}

