/** Declaration file generated by dts-gen */

export = nise;

declare const nise: {
    fakeServer: {
        addRequest: any;
        configure: any;
        create: any;
        getHTTPMethod: any;
        getRequest: any;
        handleRequest: any;
        log: any;
        logError: any;
        logger: any;
        processRequest: any;
        reset: any;
        resetBehavior: any;
        resetHistory: any;
        respond: any;
        respondWith: any;
        restore: any;
    };
    fakeServerWithClock: {
        addRequest: any;
        configure: any;
        create: any;
        getHTTPMethod: any;
        getRequest: any;
        handleRequest: any;
        log: any;
        logError: any;
        logger: any;
        processRequest: any;
        reset: any;
        resetBehavior: any;
        resetHistory: any;
        respond: any;
        respondWith: any;
        restore: any;
    };
    fakeXhr: {
        FakeXMLHttpRequest: any;
        useFakeXMLHttpRequest: any;
        xhr: {
            GlobalActiveXObject: any;
            GlobalXMLHttpRequest: any;
            XMLHttpRequest: any;
            supportsActiveX: boolean;
            supportsCORS: boolean;
            supportsTimeout: boolean;
            supportsXHR: boolean;
            workingXHR: boolean;
        };
    };
};

